// client/src/views/Home.vue
<script setup lang="ts">
import { useAuthStore } from '@/stores/auth'
const auth = useAuthStore()
</script>

<template>
  <div>
    <h2>Home</h2>
    <p>Welcome, {{ auth.username }}!</p>
    <button @click="auth.logout">Logout</button>
  </div>
  
</template>

<style scoped>
button { cursor: pointer; }
</style>

// client/src/pages/Home.tsx
import { Button, Group, Stack, Text, Title } from '@mantine/core'
import { useAuthStore } from '@/stores/auth'

export default function Home() {
  const { username, logout } = useAuthStore()

  return (
    <Stack p="lg" gap="md">
      <Title order={2}>Welcome{username ? `, ${username}` : ''}!</Title>
      <Text>You are authenticated.</Text>
      <Group>
        <Button color="red" onClick={() => logout()}>
          Logout
        </Button>
      </Group>
    </Stack>
  )
}
