// client/src/views/Signup.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { isAxiosError } from 'axios'
import { signup } from '@/api/auth'

const email = ref('')
const username = ref('')
const password = ref('')
const firstName = ref('')
const lastName = ref('')
const loading = ref(false)
const error = ref<string | null>(null)

const router = useRouter()

defineOptions({ name: 'SignupView' })

async function submit() {
  loading.value = true
  error.value = null
  try {
    await signup({ email: email.value, username: username.value, password: password.value, firstName: firstName.value, lastName: lastName.value })
    router.replace('/')
  } catch (err: unknown) {
    let message: string | undefined
    if (isAxiosError(err)) {
      const data = err.response?.data as { error?: string } | undefined
      message = data?.error
    }
    error.value = message || 'Signup failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div>
    <h2>Sign up</h2>
    <form @submit.prevent="submit">
      <label>
        Email
        <input v-model="email" type="email" autocomplete="email" />
      </label>
      <label>
        Username
        <input v-model="username" autocomplete="username" />
      </label>
      <label>
        Password
        <input type="password" v-model="password" autocomplete="new-password" />
      </label>
      <label>
        First name
        <input v-model="firstName" autocomplete="given-name" />
      </label>
      <label>
        Last name
        <input v-model="lastName" autocomplete="family-name" />
      </label>
      <button :disabled="loading">{{ loading ? 'Creating…' : 'Create account' }}</button>
    </form>
    <p v-if="error" style="color: red">{{ error }}</p>
  </div>
</template>

<style scoped>
form { display: grid; gap: .5rem; max-width: 420px; }
button { cursor: pointer; }
</style>

// client/src/pages/Signup.tsx
import { useState } from 'react'
import { Button, Group, Paper, PasswordInput, Stack, Text, TextInput, Title } from '@mantine/core'
import { Link, useNavigate } from 'react-router-dom'
import { useSignup } from '@/hooks/auth/mutations'

export default function Signup() {
  const navigate = useNavigate()
  const signupMutation = useSignup()
  const [email, setEmail] = useState('')
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')

  function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    signupMutation.mutate(
      { email, username, password, firstName, lastName },
      {
        onSuccess: () => {
          navigate('/login', { replace: true })
        },
      }
    )
  }

  const error = signupMutation.isError
    ? (() => {
        const err = signupMutation.error as any
        const fieldErrors = err?.fieldErrors
        if (fieldErrors) {
          return Object.entries(fieldErrors)
            .map(([field, message]) => `${field}: ${message}`)
            .join(', ')
        }
        return err?.message || 'Signup failed'
      })()
    : null

  return (
    <Stack align="center">
      <Paper w="100%" maw={520} p="lg" withBorder shadow="sm" radius="md" component="form" onSubmit={onSubmit}>
        <Stack>
          <Title order={3}>Create account</Title>
          {error && <Text c="red">{error}</Text>}
          <TextInput label="Email" value={email} onChange={(e) => setEmail(e.currentTarget.value)} required />
          <Group grow>
            <TextInput label="First name" value={firstName} onChange={(e) => setFirstName(e.currentTarget.value)} />
            <TextInput label="Last name" value={lastName} onChange={(e) => setLastName(e.currentTarget.value)} />
          </Group>
          <TextInput label="Username" value={username} onChange={(e) => setUsername(e.currentTarget.value)} required />
          <PasswordInput
            label="Password"
            value={password}
            onChange={(e) => setPassword(e.currentTarget.value)}
            required
          />
          <Button type="submit" loading={signupMutation.isPending} disabled={!email || !username || !password}>
            Sign up
          </Button>
          <Text size="sm">
            Already have an account? <Link to="/login">Login</Link>
          </Text>
        </Stack>
      </Paper>
    </Stack>
  )
}
