// client/src/pages/Login.tsx
import { useEffect, useState } from 'react'
import { Button, Paper, PasswordInput, Stack, Text, TextInput, Title } from '@mantine/core'
import { useAuthStore } from '@/stores/auth'
import { useLocation, useNavigate, Link } from 'react-router-dom'

export default function Login() {
  const navigate = useNavigate()
  const location = useLocation()
  const { isAuthenticated, login, initializing, bootstrap } = useAuthStore()

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (initializing) {
      void bootstrap()
    }
  }, [initializing, bootstrap])

  const redirect = new URLSearchParams(location.search).get('redirect') || '/'

  useEffect(() => {
    if (isAuthenticated) {
      navigate(redirect, { replace: true })
    }
  }, [isAuthenticated, navigate, redirect])

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    setSubmitting(true)
    setError(null)
    try {
      await login(username, password)
      navigate(redirect, { replace: true })
    } catch (e: any) {
      setError('Invalid credentials')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Stack p="lg" align="center">
      <Paper w={420} p="lg" withBorder shadow="sm" radius="md" component="form" onSubmit={onSubmit}>
        <Stack>
          <Title order={3}>Login</Title>
          {error && <Text c="red">{error}</Text>}
          <TextInput
            label="Username"
            value={username}
            onChange={(e) => setUsername(e.currentTarget.value)}
            required
          />
          <PasswordInput
            label="Password"
            value={password}
            onChange={(e) => setPassword(e.currentTarget.value)}
            required
          />
          <Button type="submit" loading={submitting} disabled={!username || !password}>
            Sign in
          </Button>
          <Text size="sm">
            No account? <Link to="/signup">Create one</Link>
          </Text>
        </Stack>
      </Paper>
    </Stack>
  )
}

// client/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useRouter, useRoute } from 'vue-router'
import { isAxiosError } from 'axios'

const username = ref('')
const password = ref('')
const loading = ref(false)
const error = ref<string | null>(null)

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()

defineOptions({ name: 'LoginView' })

async function submit() {
  loading.value = true
  error.value = null
  try {
    await auth.login(username.value, password.value)
    const redirect = (route.query.redirect as string) || '/'
    router.replace(redirect)
  } catch (err: unknown) {
    let message: string | undefined
    if (isAxiosError(err)) {
      const data = err.response?.data as { error?: string } | undefined
      message = data?.error
    }
    error.value = message || 'Login failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div>
    <h2>Login</h2>
    <form @submit.prevent="submit">
      <label>
        Username
        <input v-model="username" autocomplete="username" />
      </label>
      <label>
        Password
        <input type="password" v-model="password" autocomplete="current-password" />
      </label>
      <button :disabled="loading">{{ loading ? 'Logging in…' : 'Login' }}</button>
    </form>
    <p v-if="error" style="color: red">{{ error }}</p>
    <p>Don't have an account? <router-link to="/signup">Sign up</router-link></p>
  </div>
</template>

<style scoped>
form { display: grid; gap: .5rem; max-width: 320px; }
button { cursor: pointer; }
</style>
